#!/bin/bash

question=$1
model="openhermes2.5-mistral"

if [ -z "$2" ]; then
	echo ""
	echo "A file, such as a sql query piped as a file, required"
	echo "Example: ./askRem "What GitHub repo did I look at recently?" <(sqlite3 db 'select text from allText order by frameId desc limit 1000')"
	exit 1
fi

sources=$(./ragpipe "\"$question\"" -f ${@:2})
ollama run --verbose $model """Please answer '$question' -------------------- Below is the text that's been on screen recently. ------------- $sources ------------------ Please answer the query using the provided information about what has been on the scren recently: '$question' Do not say anything else or give any other information. Only answer the question '$question'"""
