#!/bin/bash

question=$1
model="nous-hermes2"

if [ -n "$2" ]; then
	sources=$(./ragpipe "\"$question\"" -t ${@:2} 2>/dev/null)
	ollama run --verbose $model """Please answer '$question' -------------------- Reference material: ------------- $sources ------------------ Please answer the query using the provided information: '$question' Do not say anything else or give any other information. Only answer the question '$question'"""
else
	ollama run --verbose $model $question
fi
